name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i 
    # Start a background process to monitor build progress
    - name: Monitor Build Progress
      run: |
        npm run build | while IFS= read -r line; do
          if [[ $line =~ [0-9]+% ]]; then
            echo "Build Progress: $line"
          fi
        done &

    # Execute the build command
    - run: npm run build

    # Show a message indicating build completion
    - name: Build Complete
      run: echo "Build process completed successfully!"
