name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Display message indicating build start
    - name: Start Build
      run: echo "Build process started..."

    # Execute build command
    - run: npm run build

    # Display progress messages
    - name: Build Progress
      run: |
        for ((i=5; i<=100; i+=5)); do
          echo "Build $i% Complete"
          sleep 1 # Optional: If you want to add a delay between each percentage update
        done
    # Display message indicating build completion
    - name: Build Complete
      run: echo "Build process completed successfully!"
